# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from resources import resources_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 446)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)

        self.form = QtWidgets.QWidget(MainWindow)
        self.form.setObjectName("form")

        # groupbox
        self.groupBox = QtWidgets.QGroupBox(self.form)
        self.groupBox.setGeometry(QtCore.QRect(50, 10, 730, 400))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")

        # label
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(272, 40, 186, 58))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label.setFont(font)
        self.label.setMouseTracking(False)

        self.label.setScaledContents(False)
        self.label.setObjectName("label")

        # input tài khoản
        self.userName = QtWidgets.QLineEdit(self.groupBox)
        self.userName.setEnabled(True)
        self.userName.setGeometry(QtCore.QRect(140, 140, 450, 41)) #chinhh vị trí và kích thuóc ô input
        self.userName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.userName.setClearButtonEnabled(False)
        self.userName.setObjectName("userName")

        # input mat khau
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(140, 210, 450, 41)) # chỉnh vị trí và kích thuóc ô input
        self.password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.password.setObjectName("password")

        # nút đăng nhập
        self.loginBtn = QtWidgets.QPushButton(self.groupBox)
        self.loginBtn.setGeometry(QtCore.QRect(260, 300, 211, 45))
        self.loginBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.loginBtn.setAutoDefault(False)
        self.loginBtn.setObjectName("loginBtn")

        # nút đóng
        self.closeBtn = QtWidgets.QPushButton(self.groupBox)
        self.closeBtn.setGeometry(QtCore.QRect(685, 10, 30, 30))
        self.closeBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.closeBtn.setText("")
        closeIcon = QtGui.QIcon()
        closeIcon.addPixmap(QtGui.QPixmap(":/UI/icons/close-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        print(QtGui.QPixmap(":/UI/icons/close-outline.svg").isNull())  # False nếu load ok
        self.closeBtn.setIcon(closeIcon)
        self.closeBtn.setIconSize(QtCore.QSize(25, 25))
        self.closeBtn.setObjectName("closeBtn")

        # nút ẩn
        self.hiddenBtn = QtWidgets.QPushButton(self.groupBox)
        self.hiddenBtn.setGeometry(QtCore.QRect(650, 10, 30, 30))
        self.hiddenBtn.setText("")
        hiddenIcon = QtGui.QIcon()
        hiddenIcon.addPixmap(QtGui.QPixmap(":/UI/icons/remove-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        print(QtGui.QPixmap(":/UI/icons/remove-outline.svg").isNull())  # False nếu load ok
        self.hiddenBtn.setIcon(hiddenIcon)
        self.hiddenBtn.setIconSize(QtCore.QSize(25, 25))
        self.hiddenBtn.setObjectName("hiddenBtn")


        MainWindow.setCentralWidget(self.form)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Thêm frameless + trong suốt
        MainWindow.setWindowFlags(Qt.FramelessWindowHint)
        MainWindow.setAttribute(Qt.WA_TranslucentBackground)

        # Load QSS
        self.loadStyleSheet(MainWindow)

    def loadStyleSheet(self, MainWindow):
        with open("../UI/style/style.qss", "r") as f:
            MainWindow.setStyleSheet(f.read())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.password.setPlaceholderText(_translate("MainWindow", "password"))
        self.loginBtn.setText(_translate("MainWindow", "login"))
        self.userName.setPlaceholderText(_translate("MainWindow", "user name"))
        self.label.setText(_translate("MainWindow", "LOGIN"))
